name: cryptex_shadow
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  intl: "^0.15.6"
  timeago: ^2.0.1
  url_launcher: ^3.0.3


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/loading.gif
    - assets/CryptoShadow_logo.png
    - assets/img/$pac.png
    - assets/img/act.png
    - assets/img/ada.png
    - assets/img/adx.png
    - assets/img/ae.png
    - assets/img/agi.png
    - assets/img/agrs.png
    - assets/img/aion.png
    - assets/img/amb.png
    - assets/img/amp.png
    - assets/img/ant.png
    - assets/img/appc.png
    - assets/img/ardr.png
    - assets/img/ark.png
    - assets/img/arn.png
    - assets/img/ary.png
    - assets/img/ast.png
    - assets/img/atm.png
    - assets/img/bat.png
    - assets/img/bay.png
    - assets/img/bcc.png
    - assets/img/bcd.png
    - assets/img/bch.png
    - assets/img/bcn.png
    - assets/img/bco.png
    - assets/img/bcpt.png
    - assets/img/bdl.png
    - assets/img/bela.png
    - assets/img/bix.png
    - assets/img/blcn.png
    - assets/img/blk.png
    - assets/img/block.png
    - assets/img/blz.png
    - assets/img/bnb.png
    - assets/img/bnt.png
    - assets/img/bnty.png
    - assets/img/bpt.png
    - assets/img/bq.png
    - assets/img/bqx.png
    - assets/img/brd.png
    - assets/img/btc.png
    - assets/img/btcd.png
    - assets/img/btcp.png
    - assets/img/btcz.png
    - assets/img/btg.png
    - assets/img/btm.png
    - assets/img/bts.png
    - assets/img/btx.png
    - assets/img/burst.png
    - assets/img/cdn.png
    - assets/img/cdt.png
    - assets/img/chips.png
    - assets/img/clam.png
    - assets/img/cloak.png
    - assets/img/cmt.png
    - assets/img/cnd.png
    - assets/img/cnx.png
    - assets/img/cny.png
    - assets/img/cob.png
    - assets/img/cred.png
    - assets/img/crpt.png
    - assets/img/ctr.png
    - assets/img/cvc.png
    - assets/img/dash.png
    - assets/img/dat.png
    - assets/img/data.png
    - assets/img/dbc.png
    - assets/img/dcn.png
    - assets/img/dcr.png
    - assets/img/dent.png
    - assets/img/dew.png
    - assets/img/dgb.png
    - assets/img/dgd.png
    - assets/img/dlt.png
    - assets/img/dnt.png
    - assets/img/doge.png
    - assets/img/drgn.png
    - assets/img/dta.png
    - assets/img/dtr.png
    - assets/img/ebst.png
    - assets/img/edg.png
    - assets/img/edo.png
    - assets/img/edoge.png
    - assets/img/elf.png
    - assets/img/elix.png
    - assets/img/ella.png
    - assets/img/emc.png
    - assets/img/emc2.png
    - assets/img/eng.png
    - assets/img/enj.png
    - assets/img/eos.png
    - assets/img/equa.png
    - assets/img/etc.png
    - assets/img/eth.png
    - assets/img/ethos.png
    - assets/img/etn.png
    - assets/img/etp.png
    - assets/img/eur.png
    - assets/img/evx.png
    - assets/img/exmo.png
    - assets/img/exp.png
    - assets/img/fair.png
    - assets/img/fct.png
    - assets/img/fil.png
    - assets/img/fldc.png
    - assets/img/flo.png
    - assets/img/ftc.png
    - assets/img/fuel.png
    - assets/img/fun.png
    - assets/img/game.png
    - assets/img/gas.png
    - assets/img/gbp.png
    - assets/img/gbx.png
    - assets/img/gbyte.png
    - assets/img/generic.png
    - assets/img/gno.png
    - assets/img/gnt.png
    - assets/img/grc.png
    - assets/img/grs.png
    - assets/img/gto.png
    - assets/img/gup.png
    - assets/img/gvt.png
    - assets/img/gxs.png
    - assets/img/hpb.png
    - assets/img/hsr.png
    - assets/img/html.png
    - assets/img/huc.png
    - assets/img/hush.png
    - assets/img/icn.png
    - assets/img/icx.png
    - assets/img/ignis.png
    - assets/img/ink.png
    - assets/img/ins.png
    - assets/img/ion.png
    - assets/img/iop.png
    - assets/img/iost.png
    - assets/img/itc.png
    - assets/img/jnt.png
    - assets/img/jpy.png
    - assets/img/kcs.png
    - assets/img/kin.png
    - assets/img/kmd.png
    - assets/img/knc.png
    - assets/img/krb.png
    - assets/img/lbc.png
    - assets/img/lend.png
    - assets/img/link.png
    - assets/img/lkk.png
    - assets/img/lrc.png
    - assets/img/lsk.png
    - assets/img/ltc.png
    - assets/img/lun.png
    - assets/img/maid.png
    - assets/img/mana.png
    - assets/img/mcap.png
    - assets/img/mco.png
    - assets/img/mda.png
    - assets/img/mds.png
    - assets/img/med.png
    - assets/img/miota.png
    - assets/img/mkr.png
    - assets/img/mln.png
    - assets/img/mnx.png
    - assets/img/mod.png
    - assets/img/mona.png
    - assets/img/mth.png
    - assets/img/mtl.png
    - assets/img/music.png
    - assets/img/nano.png
    - assets/img/nas.png
    - assets/img/nav.png
    - assets/img/ncash.png
    - assets/img/ndz.png
    - assets/img/nebl.png
    - assets/img/neo.png
    - assets/img/neos.png
    - assets/img/ngc.png
    - assets/img/nlc2.png
    - assets/img/nlg.png
    - assets/img/nmc.png
    - assets/img/nuls.png
    - assets/img/nxs.png
    - assets/img/nxt.png
    - assets/img/oax.png
    - assets/img/omg.png
    - assets/img/omni.png
    - assets/img/ont.png
    - assets/img/ost.png
    - assets/img/ox.png
    - assets/img/pac.png
    - assets/img/part.png
    - assets/img/pasl.png
    - assets/img/pay.png
    - assets/img/pink.png
    - assets/img/pirl.png
    - assets/img/pivx.png
    - assets/img/plr.png
    - assets/img/poa.png
    - assets/img/poe.png
    - assets/img/poly.png
    - assets/img/pot.png
    - assets/img/powr.png
    - assets/img/ppc.png
    - assets/img/ppp.png
    - assets/img/ppt.png
    - assets/img/prl.png
    - assets/img/pura.png
    - assets/img/qash.png
    - assets/img/qiwi.png
    - assets/img/qlc.png
    - assets/img/qrl.png
    - assets/img/qsp.png
    - assets/img/qtum.png
    - assets/img/r.png
    - assets/img/rads.png
    - assets/img/rcn.png
    - assets/img/rdd.png
    - assets/img/rdn.png
    - assets/img/rep.png
    - assets/img/req.png
    - assets/img/rhoc.png
    - assets/img/ric.png
    - assets/img/rise.png
    - assets/img/rlc.png
    - assets/img/rpx.png
    - assets/img/rub.png
    - assets/img/salt.png
    - assets/img/san.png
    - assets/img/sbd.png
    - assets/img/sberbank.png
    - assets/img/sc.png
    - assets/img/sky.png
    - assets/img/sls.png
    - assets/img/smart.png
    - assets/img/sngls.png
    - assets/img/snm.png
    - assets/img/snt.png
    - assets/img/sonm.png
    - assets/img/spank.png
    - assets/img/sphtx.png
    - assets/img/srn.png
    - assets/img/start.png
    - assets/img/steem.png
    - assets/img/storj.png
    - assets/img/storm.png
    - assets/img/strat.png
    - assets/img/sub.png
    - assets/img/sys.png
    - assets/img/taas.png
    - assets/img/tau.png
    - assets/img/tel.png
    - assets/img/theta.png
    - assets/img/tix.png
    - assets/img/tkn.png
    - assets/img/tnb.png
    - assets/img/tnc.png
    - assets/img/tnt.png
    - assets/img/trig.png
    - assets/img/trx.png
    - assets/img/tzc.png
    - assets/img/ubq.png
    - assets/img/unity.png
    - assets/img/usd.png
    - assets/img/usdt.png
    - assets/img/utk.png
    - assets/img/ven.png
    - assets/img/veri.png
    - assets/img/via.png
    - assets/img/vib.png
    - assets/img/vibe.png
    - assets/img/vivo.png
    - assets/img/vrc.png
    - assets/img/vtc.png
    - assets/img/wabi.png
    - assets/img/waves.png
    - assets/img/wax.png
    - assets/img/wgr.png
    - assets/img/wings.png
    - assets/img/wpr.png
    - assets/img/wtc.png
    - assets/img/xas.png
    - assets/img/xbc.png
    - assets/img/xby.png
    - assets/img/xcp.png
    - assets/img/xdn.png
    - assets/img/xem.png
    - assets/img/xlm.png
    - assets/img/xmg.png
    - assets/img/xmr.png
    - assets/img/xmy.png
    - assets/img/xp.png
    - assets/img/xpa.png
    - assets/img/xpm.png
    - assets/img/xrp.png
    - assets/img/xtz.png
    - assets/img/xuc.png
    - assets/img/xvc.png
    - assets/img/xvg.png
    - assets/img/xzc.png
    - assets/img/yoyow.png
    - assets/img/zcl.png
    - assets/img/zec.png
    - assets/img/zen.png
    - assets/img/zil.png
    - assets/img/zrx.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/FiraCode-Regular.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
